# Лабораторная работа 2

# Встроенные типы объектов в Python

##### Белоус Мария Руслановна ,14.03.2025

## 1.Числовые типы(Numbers)

## Задание 1. Построить иерархии встроенных типов в Python 

Встроенные типы делятся на:

1.Числа
- Целые числа(`int`),неизменяемые
- Числа с плавающей точкой(`float`),неизменяемые
- Комплексные числа (`complex`),неизменяемые
- Булевый тип (`bool`) - наследуюется от int, неизменяемые

2.Коллекции 
- Последовательности:
- строки(`str`),неупорядоченные,неизменяемые.
- списки (`list`),упорядоченные,изменяемые
- кортеджи(`tuple`),упорядоченные,изменяемые
- Отображения:
- словари(`dict`),неупорядоченные,изменяемые
- Множества:
- множества(`set`),неупорядоченные,изменяемые 


Пример литералов для создания обьекта:
- `42`- для `int`
- `3.14`-для `flot`
- `1 + 1j`-для `complex`
- `True`,`False`-для `bool`
- `"Hello"`-для `str`
- `[1,2,3]`-для `list`
- `(1,2,3)- для `typle`
- `{'a': 1, 'b' : 2}`- для `dict`
-  `{1,2,3}`-для `set`

## Задание 2

## Задание 2.1 


### Тема 2. Объект как фундаментальное понятие в Python.
### Встроенные типы объектов: 

- 2.1 Понятие объекта.Арбитуры.Методы.Встроенные типы объектов
- 2.2 Встроенные типы объектов ,представляющих числа
- 2.3 Встроенные типы последовательностей:str,list,tuple
- 2.4 Встроенный тип отображения:dict
- 2.5 Встроенный тип множества:set
- 2.6 Встроенный булевой тип
- 2.7 Изменяемые и неизменяемые встроенные типы объектов
- 2.8 Интерфейс объекта:операции и методы
- 2.9 Переменная
- 2.10 Выражение спискового включения
- 2.11 Форматированный вывод строк
- 2.12 Файловый объект 

## Задание 2.2

#### 2.2 Встроенные типы объектов ,представляющие числа

In [3]:
import decimal 
a = decimal.Decimal('0.1')
b = decimal.Decimal('0.2')
sum = a + b 
multi = a * b 
division = a / b
print(a,b)
print(sum,multi,division)

0.1 0.2
0.3 0.02 0.5


In [6]:
from fractions import Fraction 
x = Fraction (1,2)
y = Fraction (2,3)
sum = x + y
multi = x * y
division = x / y
print(x,y)
print(sum,multi,division)

1/2 2/3
7/6 1/3 3/4


## 2.3. Встроенные типы последовательностей: str,list, tuple 

In [7]:
S = 'spam'
print(S)
S = S[:1] + '1' + S[2:]
print(S)

spam
s1am


S[:1] — срез строки, позволяющий извлечь все символы от начала строки S до индекса 1 (не включая символ на этом индексе). Например, если S = 'spam', то результат S[:1] будет 's'.

'l' — конкатенация строк, при которой в исходную строку добавляется новый символ 'l'.

S[2:] — срез, который выбирает все символы строки S, начиная с позиции 2 и до конца. Для строки 'spam' выполнение S[2:] даст 'am'.

Можно ли выполнить эту операцию, используя только индексацию и конкатенацию? Нет, это невозможно. В Python строки являются неизменяемыми (immutable), поэтому изменение конкретного символа путем присваивания по индексу не поддерживается. Строки нельзя изменить напрямую, ведь они остаются неизменными в ходе выполнения программы.

Для списка (`list`):

In [9]:
L = ['s','p','a','m']
L[1] = '1'
print(L)

['s', '1', 'a', 'm']


Для кортежа `(tuple)`

In [10]:
T = ('s','p','a','m')
T = T[:1] + ('1',) + T[2:]
print(T)

('s', '1', 'a', 'm')


## 2.4 Встроенный тип отображения:dict

In [15]:
privathayainfimaziya = {
    "Имя": "Мария",
    "Фамилия": "Белоус",
    "Отчество": "Руслановна",
    "Возраст": 18,
    "Место работы": "BSU",
    "Адрес": "Минск,Беларусь",
    "email":"belous_masha@internet.ru",
    "Телефон": "+375444908322"
}
name = privathayainfimaziya["Имя"]
age = privathayainfimaziya["Возраст"]
email = privathayainfimaziya["email"]
print(name , age , email)

Мария 18 belous_masha@internet.ru


тот же словарь будет более удобен, так как:

- Легко получать доступ к значениям по ключам.

- Удобно добавлять и изменять данные.

- Понятная структура данных.

a tuple менее приятен, т.к. к примеру требуют больше усилий для доступа к значениям по индексу.

## 2.5 Встроенный тип множества: set

In [19]:
sunsset = "sssuunnset"
sunset = set(sunsset)
riseagain = ''.join(sunset)
print(sunsset)
print(riseagain)

sssuunnset
setnu


получилость `setnu`,а должно было быть `sunet`,видимо,порядок теряется

### 2.8 Интерфейс объекта:операции и методы

### 2.8.1

In [2]:
s = "Hello world"
scount = s.count('o')
sindex = s.index('o')
print(scount,sindex)

2 4


In [3]:
lst = [1,2,3,2,1]
lcount = lst.count(2)
lindex = lst.index(2)
print(lcount,lindex)


2 1


In [4]:
tpl = (1,2,3,2,1)
tcount = tpl.count(2)
tindex = tpl.index(2)
print(tcount,tindex)

2 1


### 2.8.2

### Пример выражения с тремя строковыми методами

In [7]:
s = "sounds great"
result = s.upper().replace("GREAT","AWFUL").split()
print(result)

['SOUNDS', 'AWFUL']


#### Спецификации 

- `upper`:Преобразует все буквы строки в верхний регистр
- `replace`: Заменяет все вхождения подстроки на новые
- `split`: Разбивает строку на список подстрок по заданному разделителю 

### 2.8.3

In [10]:
lst = [1,3,3]
lst.append(4)
print(lst)

[1, 3, 3, 4]


In [11]:
lst = [1,2,3]
lst.extend([4,5, 'g'])
print(lst)

[1, 2, 3, 4, 5, 'g']


In [12]:
lst = [1,2,3]
lst.insert(1,5000)
print(lst)

[1, 5000, 2, 3]


### 2.8.4

lst = ["dlin","dlinana","dlina"]
lst.sort(key=len) # по длине
print(lst)

### 2.8.5

In [19]:
d = {i: "-7" for i in range(100)}
print(d)

{0: '-7', 1: '-7', 2: '-7', 3: '-7', 4: '-7', 5: '-7', 6: '-7', 7: '-7', 8: '-7', 9: '-7', 10: '-7', 11: '-7', 12: '-7', 13: '-7', 14: '-7', 15: '-7', 16: '-7', 17: '-7', 18: '-7', 19: '-7', 20: '-7', 21: '-7', 22: '-7', 23: '-7', 24: '-7', 25: '-7', 26: '-7', 27: '-7', 28: '-7', 29: '-7', 30: '-7', 31: '-7', 32: '-7', 33: '-7', 34: '-7', 35: '-7', 36: '-7', 37: '-7', 38: '-7', 39: '-7', 40: '-7', 41: '-7', 42: '-7', 43: '-7', 44: '-7', 45: '-7', 46: '-7', 47: '-7', 48: '-7', 49: '-7', 50: '-7', 51: '-7', 52: '-7', 53: '-7', 54: '-7', 55: '-7', 56: '-7', 57: '-7', 58: '-7', 59: '-7', 60: '-7', 61: '-7', 62: '-7', 63: '-7', 64: '-7', 65: '-7', 66: '-7', 67: '-7', 68: '-7', 69: '-7', 70: '-7', 71: '-7', 72: '-7', 73: '-7', 74: '-7', 75: '-7', 76: '-7', 77: '-7', 78: '-7', 79: '-7', 80: '-7', 81: '-7', 82: '-7', 83: '-7', 84: '-7', 85: '-7', 86: '-7', 87: '-7', 88: '-7', 89: '-7', 90: '-7', 91: '-7', 92: '-7', 93: '-7', 94: '-7', 95: '-7', 96: '-7', 97: '-7', 98: '-7', 99: '-7'}


In [21]:
a = [1,2,3]
a.append(a)
print(a)

[1, 2, 3, [...]]


In [22]:
slovar = {'od': 'tr'}
slovar['uf'] = slovar
print(slovar) #Output: {'key': 'value','self':{...}}

{'od': 'tr', 'uf': {...}}


In [23]:
obj = [13]
a = b = c = d = obj
print(a,b,c,d)

[13] [13] [13] [13]


### Три различных способа копирования списка.

In [24]:
origin = [1,2,3]
copy = list(origin)
print(copy)

[1, 2, 3]


In [25]:
origin = [1,2,3]
copy = origin.copy()
print(copy)

[1, 2, 3]


In [26]:
origin = [1,2,3]
copy = origin 
print(copy)

[1, 2, 3]


### 2.10 Выражение спискового включения 

In [27]:
nechet = {x for x in range(10) if x % 2 == 1}
print(nechet)

{1, 3, 5, 7, 9}


In [29]:
matrix = [[ i + j for j in range(8)] for i in range(7)]
for row in matrix:
   print(row)

[0, 1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 6, 7, 8]
[2, 3, 4, 5, 6, 7, 8, 9]
[3, 4, 5, 6, 7, 8, 9, 10]
[4, 5, 6, 7, 8, 9, 10, 11]
[5, 6, 7, 8, 9, 10, 11, 12]
[6, 7, 8, 9, 10, 11, 12, 13]


In [30]:
import numpy as np
matrix = np.arange(56).reshape(7,8)
print(matrix)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]]


In [31]:
slojnidict = {i:{'a':i ** 2} for i in range(4)}
print(slojnidict)

{0: {'a': 0}, 1: {'a': 1}, 2: {'a': 4}, 3: {'a': 9}}


### 2.11 Форматированный вывод строк

In [34]:
variable = 52
fstring = f'{variable =:3}'
print(fstring)

variable = 52


In [35]:
variable = 52
f1string = 'variable = %3d' % variable
print(f1string)

variable =  52


In [36]:
variable = 52
f2string = 'variable = {:3}'.format(variable)
print(f2string)

variable =  52


In [37]:
expression = 52 * 2
estring = f'{expression=:.0f}'
print(estring)

expression=104


In [39]:
expression = 52 * 2 
e1string = 'expression=%.1f' % expression
print(e1string)

expression=104.0


In [40]:
expression = 52 * 2
e2string = 'expression={:.2f}'.format(expression)
print(e2string)

expression=104.00


### 2.12 Файловый объект 

In [2]:
#1. Запись списка чисел в файл
with open("numbers.txt", "w") as file:
    file.writelines([f"{i}\n" for i in range(1, 6)])  # Записываем числа от 1 до 5

# 2. Чтение всего файла
with open("numbers.txt", "r") as file:
    content = file.read()
    print("Содержимое файла:\n", content)

# 3. Чтение первой строки
with open("numbers.txt", "r") as file:
    first_line = file.readline()
    print("Первая строка:", first_line.strip())

# 4. Чтение всех строк в список
with open("numbers.txt", "r") as file:
    lines = file.readlines()
    print("Список строк:", lines)

# 5. Явное закрытие файла
file = open("numbers.txt", "r")
print("Последнее чтение:", file.read())
file.close()  # Закрываем файл явно


Содержимое файла:
 1
2
3
4
5

Первая строка: 1
Список строк: ['1\n', '2\n', '3\n', '4\n', '5\n']
Последнее чтение: 1
2
3
4
5



## Задание 2.3 

## Фрагмент 1

` print ('\c \xc6 `)

Ошибка возникает из-за \c, которая не является правильной escape-последовательностью. Python не знает, что с ней делать, поэтому выдает предупреждение.

## Фрагмент 2

` str1[10]`

Ошибка IndexError возникает, потому что индекс 10 выходит за пределы длины строки str1. В Python индексы начинаются с 0, и если строка короче 11 символов, этот индекс недоступен.

## Фрагмент 3

`[1] + '1'`

Ошибка TypeError возникает, потому что в Python нельзя объединять список и строку напрямую.

## Фрагмент 4

` dict1 ['two']`

Ошибка KeyError возникает, потому что ключ 'two' отсутствует в словаре dict1.

## Фрагмент 5

`t = [1,2], {1:2}, {1,2}; t[0] = 0`

Ошибка TypeError возникает, потому что t является кортежем, а кортежи в Python неизменяемы.

## Фрагмент 6

` {1, 'str',(1,)}.add([1]) `

Ошибка TypeError возникает, потому что нельзя добавлять список [1] в множество.

## Фрагмент 7

` print(dict1.get('one'), dict1.get('three')) `

`dict1['three']`

Ошибка KeyError возникает, потому что вы пытаетесь получить значение по ключу 'three', который отсутствует в словаре dict1. Метод .get() возвращает None, если ключ не найден, но доступ к несуществующему ключу с помощью dict1['three'] вызывает ошибку.

## Фрагмент 8 
`print(s, s.find('-'))`

`s.index('-')`

Ошибка ValueError возникает, потому что метод index() не находит подстроку '-' в строке s.

## Фрагмент 9 
`a = 1  # создание переменной`

`a, d`

Ошибка NameError возникает, потому что переменная d не определена.

## Фрагмент 10
`print(abs(-1))`

`abs = 5`

`print(abs(-1))`

Ошибка TypeError возникает, потому что после присвоения abs = 5, abs больше не ссылается на функцию abs(), а становится целым числом.

# Задание 3. Ответы на контрольные вопросы из книги М. Лутца

# 1. Глава 4, вопрос 6: Что такое "полиморфизм" и почему о нем нужно заботиться?

Полиморфизм означает, что смысл операции (например, +) зависит от объектов, к которым она применяется. Это позволяет использовать один и тот же оператор для различных типов данных, что делает код более гибким и универсальным.

Примеры:

1.Сложение чисел

In [8]:
a3 = 1
b3 = 99
result = a3 + b3
print(result)

100


2. Сложение строк

In [9]:
str5 = "Wit beyond measure "
str6 = "is a man’s greatest treasure."
result = str5 + str6
print(result)

Wit beyond measure is a man’s greatest treasure.


3.Сложение списков

In [10]:
list01 = [1, 2, 3]
list02 = [4, 5, 6]
result01 = list01 + list02
print(result01)

[1, 2, 3, 4, 5, 6]


# 2. Глава 5, вопрос 7: Как можно преобразовывать целое число в число с плавающей точкой?

Для преобразования целого числа в число с плавающей точкой в Python можно использовать функцию float(). Также смешивание целых чисел и чисел с плавающей точкой в выражениях приводит к автоматическому преобразованию целых чисел в числа с плавающей точкой. Кроме того, операция деления (/) в Python 3 всегда возвращает число с плавающей точкой, даже если оба операнда являются целыми.

Примеры:

1.Использование функции float()


In [11]:
integer_val01 = 8
float_val01 = float(integer_val01)
print(float_val01)

8.0


2.Смешивание типов в выражении

In [15]:

a4 = 8
b4 = 2.99
result04 = a4 + b4
print(result04)

10.99


3. Опреция деления

In [16]:
x9 = 1000
y9 = 7
result = x9 / y9
print(result)

142.85714285714286


Применение float() и автоматическое преобразование типов делает Python гибким в работе с числовыми данными, что упрощает математические вычисления и работу с различными типами данных.

# 3. Глава 6, вопрос 2: Изменяют ли три оператора значение, выводимое для A?

In [17]:
A = ["spam"]
B = A
B[0] = "shrubbery"

Да, теперь для A выводится ["shrubbery"]. A и B ссылаются на один и тот же список. Когда мы изменяем первый элемент списка через B, это изменение также видно в A, потому что обе переменные указывают на один и тот же объект.

Пример:

In [18]:
print(B)
print(A)

['shrubbery']
['shrubbery']


Изменение происходит не в самих переменных, а в списке, на который они ссылаются. Поэтому, когда мы изменяем его через B, это видно и в A.

# 4. Глава 7, вопрос 6: Сколько символов в строке "a\nb\x0f\000d"?

В строке "a\nb\x0f\000d" содержится 6 символов: a, \n (символ новой строки), b, \x0f, \000, d.

Пример:

In [19]:
string01 = "a\nb\x0f\000d"

length01 = len(string01)
print("Длина строки:", length01)

for char in string01:
    print(f"Символ: {char}, Код: {ord(char)}")

Длина строки: 6
Символ: a, Код: 97
Символ: 
, Код: 10
Символ: b, Код: 98
Символ: , Код: 15
Символ: , Код: 0
Символ: d, Код: 100


Используя функцию len(), мы можем подтвердить, что в строке 6 символов. Функция ord() показывает значения кодов для каждого символа, что позволяет увидеть, как интерпретируются управляющие последовательности.

# 5. Глава 8, вопрос 3: Назовите четыре операции, которые изменяют списковый объект на месте в Python.

1. append() — добавляет элемент в конец списка:

In [20]:
list08 = [1, 2, 3]
list08.append(9)
print(list08)

[1, 2, 3, 9]


2. extend() — добавляет элементы из другого списка в конец текущего списка:

In [21]:
list08.extend([6, 5])
print(list08)

[1, 2, 3, 9, 6, 5]


3.sort() — сортирует элементы списка на месте:

In [22]:
list08.sort()
print(list08)

[1, 2, 3, 5, 6, 9]


4.reverse() — разворачивает список на месте:

In [23]:
list08.reverse()
print(list08)

[9, 6, 5, 3, 2, 1]


Эти методы изменяют сам объект списка, а не создают новый.

# 6. Глава 9, вопрос 6: Когда в Python объект считается истинным?

Объект в Python считается истинным, если он соответствует следующим условиям:

- нулевое число: Любое число, кроме 0 (например, 1, -1, 3.14), является истинным.
- Непустая коллекция: Это могут быть непустые списки, кортежи, множества, строки или словари (например, [1, 2], 'hello', {1: 'a'}).
- Встроенные значения: Значения True и False также являются истинными и ложными соответственно, где True эквивалентно 1, а False эквивалентно 0.
Примеры:

In [25]:
# Истинные объекты
print(bool(1))
print(bool(-1))
print(bool(3.14))
print(bool("hello"))
print(bool([1, 2]))
print(bool({'a': 1}))

# Ложные объекты
print(bool(0))
print(bool(0.0))  
print(bool(""))   
print(bool([]))   
print(bool({})) 
print(bool(None)) 

True
True
True
True
True
True
False
False
False
False
False
False


Понимание истинности и ложности объектов в Python позволяет более эффективно управлять логическими операциями и условиями в коде.